server:
  port: 8081
spring:
  application:
    name: spring-cloud-consul-consumer

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        heartbeat:
          enabled: true
        healthCheckPath: /actuator/health
        enabled: true
ribbon:
  eager-load:
    clients: spring-cloud-consul-producer

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
spring-cloud-consul-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #配置客户端provider的服务列表
    #listOfServers: 127.0.0.1:9907,127.0.0.1:9907
