server:
  port: 80
spring:
  application:
    name: service-zull
  cloud:
    #consul注册中心
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        heartbeat:
          enabled: true
        healthCheckPath: /actuator/health
        enabled: true
#zuul相关配置

